/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/server/{id}": {
    get: operations["getServer"];
    put: operations["updateServer"];
    delete: operations["deleteServer"];
  };
  "/channel/{id}": {
    get: operations["getChannel"];
    put: operations["updateChannel"];
    delete: operations["deleteChannel"];
  };
  "/bot/{id}": {
    get: operations["getBot"];
    put: operations["updateBot"];
    delete: operations["deleteBot"];
  };
  "/server/": {
    get: operations["listServers"];
    post: operations["createServer"];
  };
  "/download/": {
    get: operations["listDownloads"];
    post: operations["addDownload"];
  };
  "/channel/": {
    get: operations["listChannels"];
    post: operations["createChannel"];
  };
  "/bot/": {
    get: operations["listBots"];
    post: operations["createBot"];
  };
  "/download/{id}": {
    get: operations["getDownload"];
    delete: operations["removeDownload"];
  };
  "/download/failed": {
    get: operations["failedDownloads"];
  };
  "/download/active/": {
    get: operations["getActiveDownloads"];
  };
}

export interface components {
  schemas: {
    ServerFormTO: {
      name?: string;
      serverUrl?: string;
    };
    ServerTO: {
      /** Format: uuid */
      id: string;
      name: string;
      serverUrl: string;
      /** Format: date-time */
      creationDate: string;
    };
    ChannelFormTO: {
      name?: string;
      bla?: string;
    };
    ChannelTO: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      date: string;
    };
    BotFormTO: {
      name?: string;
      pattern?: string;
      /** Format: uuid */
      serverId?: string;
      /** Format: uuid */
      channelId?: string;
      /** Format: int64 */
      maxParallelDownloads?: number;
    };
    BotTO: {
      /** Format: uuid */
      id: string;
      server: components["schemas"]["Server"];
      channel: components["schemas"]["Channel"];
      name: string;
      pattern: string;
      /** Format: date-time */
      creationDate: string;
      /** Format: int64 */
      maxParallelDownloads: number;
    };
    Channel: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** Format: date-time */
      date?: string;
    };
    Server: {
      /** Format: uuid */
      id?: string;
      name?: string;
      serverUrl?: string;
      /** Format: date-time */
      creationDate?: string;
    };
    DownloadFormTO: {
      /** Format: uuid */
      targetBotId?: string;
      fileRefId?: string;
    };
    /** @enum {string} */
    DownloadState:
      | "Connecting"
      | "Done"
      | "Error"
      | "Finalizing"
      | "Preparing"
      | "Prepared"
      | "Ready"
      | "Restarting"
      | "Stopped"
      | "Transmitting"
      | "Unknown";
    DownloadTO: {
      /** Format: uuid */
      id: string;
      filename: string;
      filesize: string;
      status?: components["schemas"]["DownloadState"];
      statusMessage?: string;
      /** Format: double */
      progress?: number;
      averageSpeed?: string;
      timeRemaining?: string;
    } & {
      bot: unknown;
    };
  };
}

export interface operations {
  getServer: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServerTO"];
        };
      };
    };
  };
  updateServer: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServerTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServerFormTO"];
      };
    };
  };
  deleteServer: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  getChannel: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ChannelTO"];
        };
      };
    };
  };
  updateChannel: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ChannelTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChannelFormTO"];
      };
    };
  };
  deleteChannel: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*":
            | "100 CONTINUE"
            | "101 SWITCHING_PROTOCOLS"
            | "102 PROCESSING"
            | "103 EARLY_HINTS"
            | "200 OK"
            | "201 CREATED"
            | "202 ACCEPTED"
            | "203 NON_AUTHORITATIVE_INFORMATION"
            | "204 NO_CONTENT"
            | "205 RESET_CONTENT"
            | "206 PARTIAL_CONTENT"
            | "207 MULTI_STATUS"
            | "208 ALREADY_REPORTED"
            | "226 IM_USED"
            | "300 MULTIPLE_CHOICES"
            | "301 MOVED_PERMANENTLY"
            | "302 FOUND"
            | "303 SEE_OTHER"
            | "304 NOT_MODIFIED"
            | "307 TEMPORARY_REDIRECT"
            | "308 PERMANENT_REDIRECT"
            | "400 BAD_REQUEST"
            | "401 UNAUTHORIZED"
            | "402 PAYMENT_REQUIRED"
            | "403 FORBIDDEN"
            | "404 NOT_FOUND"
            | "405 METHOD_NOT_ALLOWED"
            | "406 NOT_ACCEPTABLE"
            | "407 PROXY_AUTHENTICATION_REQUIRED"
            | "408 REQUEST_TIMEOUT"
            | "409 CONFLICT"
            | "410 GONE"
            | "411 LENGTH_REQUIRED"
            | "412 PRECONDITION_FAILED"
            | "413 CONTENT_TOO_LARGE"
            | "413 PAYLOAD_TOO_LARGE"
            | "414 URI_TOO_LONG"
            | "415 UNSUPPORTED_MEDIA_TYPE"
            | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
            | "417 EXPECTATION_FAILED"
            | "418 I_AM_A_TEAPOT"
            | "421 MISDIRECTED_REQUEST"
            | "422 UNPROCESSABLE_CONTENT"
            | "422 UNPROCESSABLE_ENTITY"
            | "423 LOCKED"
            | "424 FAILED_DEPENDENCY"
            | "425 TOO_EARLY"
            | "426 UPGRADE_REQUIRED"
            | "428 PRECONDITION_REQUIRED"
            | "429 TOO_MANY_REQUESTS"
            | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
            | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
            | "500 INTERNAL_SERVER_ERROR"
            | "501 NOT_IMPLEMENTED"
            | "502 BAD_GATEWAY"
            | "503 SERVICE_UNAVAILABLE"
            | "504 GATEWAY_TIMEOUT"
            | "505 HTTP_VERSION_NOT_SUPPORTED"
            | "506 VARIANT_ALSO_NEGOTIATES"
            | "507 INSUFFICIENT_STORAGE"
            | "508 LOOP_DETECTED"
            | "509 BANDWIDTH_LIMIT_EXCEEDED"
            | "510 NOT_EXTENDED"
            | "511 NETWORK_AUTHENTICATION_REQUIRED";
        };
      };
    };
  };
  getBot: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["BotTO"];
        };
      };
    };
  };
  updateBot: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["BotTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BotFormTO"];
      };
    };
  };
  deleteBot: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*":
            | "100 CONTINUE"
            | "101 SWITCHING_PROTOCOLS"
            | "102 PROCESSING"
            | "103 EARLY_HINTS"
            | "200 OK"
            | "201 CREATED"
            | "202 ACCEPTED"
            | "203 NON_AUTHORITATIVE_INFORMATION"
            | "204 NO_CONTENT"
            | "205 RESET_CONTENT"
            | "206 PARTIAL_CONTENT"
            | "207 MULTI_STATUS"
            | "208 ALREADY_REPORTED"
            | "226 IM_USED"
            | "300 MULTIPLE_CHOICES"
            | "301 MOVED_PERMANENTLY"
            | "302 FOUND"
            | "303 SEE_OTHER"
            | "304 NOT_MODIFIED"
            | "307 TEMPORARY_REDIRECT"
            | "308 PERMANENT_REDIRECT"
            | "400 BAD_REQUEST"
            | "401 UNAUTHORIZED"
            | "402 PAYMENT_REQUIRED"
            | "403 FORBIDDEN"
            | "404 NOT_FOUND"
            | "405 METHOD_NOT_ALLOWED"
            | "406 NOT_ACCEPTABLE"
            | "407 PROXY_AUTHENTICATION_REQUIRED"
            | "408 REQUEST_TIMEOUT"
            | "409 CONFLICT"
            | "410 GONE"
            | "411 LENGTH_REQUIRED"
            | "412 PRECONDITION_FAILED"
            | "413 CONTENT_TOO_LARGE"
            | "413 PAYLOAD_TOO_LARGE"
            | "414 URI_TOO_LONG"
            | "415 UNSUPPORTED_MEDIA_TYPE"
            | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
            | "417 EXPECTATION_FAILED"
            | "418 I_AM_A_TEAPOT"
            | "421 MISDIRECTED_REQUEST"
            | "422 UNPROCESSABLE_CONTENT"
            | "422 UNPROCESSABLE_ENTITY"
            | "423 LOCKED"
            | "424 FAILED_DEPENDENCY"
            | "425 TOO_EARLY"
            | "426 UPGRADE_REQUIRED"
            | "428 PRECONDITION_REQUIRED"
            | "429 TOO_MANY_REQUESTS"
            | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
            | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
            | "500 INTERNAL_SERVER_ERROR"
            | "501 NOT_IMPLEMENTED"
            | "502 BAD_GATEWAY"
            | "503 SERVICE_UNAVAILABLE"
            | "504 GATEWAY_TIMEOUT"
            | "505 HTTP_VERSION_NOT_SUPPORTED"
            | "506 VARIANT_ALSO_NEGOTIATES"
            | "507 INSUFFICIENT_STORAGE"
            | "508 LOOP_DETECTED"
            | "509 BANDWIDTH_LIMIT_EXCEEDED"
            | "510 NOT_EXTENDED"
            | "511 NETWORK_AUTHENTICATION_REQUIRED";
        };
      };
    };
  };
  listServers: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServerTO"][];
        };
      };
    };
  };
  createServer: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServerTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServerFormTO"];
      };
    };
  };
  listDownloads: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DownloadTO"][];
        };
      };
    };
  };
  addDownload: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DownloadTO"][];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DownloadFormTO"];
      };
    };
  };
  listChannels: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ChannelTO"][];
        };
      };
    };
  };
  createChannel: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ChannelTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChannelFormTO"];
      };
    };
  };
  listBots: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["BotTO"][];
        };
      };
    };
  };
  createBot: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["BotTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BotFormTO"];
      };
    };
  };
  getDownload: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DownloadTO"];
        };
      };
    };
  };
  removeDownload: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  failedDownloads: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DownloadTO"][];
        };
      };
    };
  };
  getActiveDownloads: {
    parameters: {
      query: {
        active: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DownloadTO"][];
        };
      };
    };
  };
}

export interface external {}
