/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/servers/": {
    get: operations["getAllServers"];
    post: operations["addServer"];
    delete: operations["delete"];
  };
  "/channels/": {
    get: operations["allChannels"];
    post: operations["addChannel"];
  };
  "/bots/": {
    get: operations["getAllBots"];
    post: operations["addBot"];
  };
  "/servers/example": {
    get: operations["getExampleServer"];
  };
}

export interface components {
  schemas: {
    ServerForm: {
      name?: string;
      serverUrl?: string;
    };
    ChannelForm: {
      name?: string;
      bla?: string;
    };
    TargetBotForm: {
      name?: string;
      pattern?: string;
      /** Format: uuid */
      serverId?: string;
      /** Format: uuid */
      channelId?: string;
      /** Format: int64 */
      maxParallelDownloads?: number;
    };
    Server: {
      /** Format: uuid */
      id?: string;
      name?: string;
      serverUrl?: string;
      /** Format: date-time */
      creationDate?: string;
    };
    ServerTO: {
      /** Format: uuid */
      id?: string;
      name?: string;
      serverUrl?: string;
    };
    Channel: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** Format: date-time */
      date?: string;
    };
    Bot: {
      /** Format: uuid */
      id?: string;
      server?: components["schemas"]["Server"];
      channel?: components["schemas"]["Channel"];
      name?: string;
      pattern?: string;
      /** Format: date-time */
      creationDate?: string;
      /** Format: int64 */
      maxParallelDownloads?: number;
    };
  };
}

export interface operations {
  getAllServers: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServerTO"][];
        };
      };
    };
  };
  addServer: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServerForm"];
      };
    };
  };
  delete: {
    parameters: {
      query: {
        serverId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  allChannels: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Channel"][];
        };
      };
    };
  };
  addChannel: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChannelForm"];
      };
    };
  };
  getAllBots: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Bot"][];
        };
      };
    };
  };
  addBot: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetBotForm"];
      };
    };
  };
  getExampleServer: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Server"][];
        };
      };
    };
  };
}

export interface external {}
