version: '3.3'
services:
    run:
        image: ghcr.io/maggiwuerze/xdccwebloader:latest
        container_name: xdcc_webloader
        restart: unless-stopped
        volumes:
            - '/path/to/your/docker/folder/xdcc:/xdcc_webloader/xdcc'
            - '/path/to/your/docker/folder/data:/xdcc_webloader/data'
        ports:
            - '9999:8080'
        environment:
            - XDCC_DB_TYPE=org.hibernate.dialect.PostgreSQLDialect
            - XDCC_DB_URL=postgresql://mediaserver:49153/postgres
            - XDCC_DB_USER=sa
            - XDCC_DB_PASSWORD=sa