name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
         java-version: 1.17
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Build with Gradle      
        run: ./gradlew jar
        
      - name: Build Docker image
        run: |
          docker build -t xdcc_webloader .
          docker tag xdcc_webloader my-docker-registry/my-spring-boot-app
          docker push my-docker-registry/my-spring-boot-app
